export type ActivitySchedule = 'today' | 'tomorrow' | 'weekend'
export type ActivityBudget = 'low' | 'mid' | 'high'

export interface Activity {
  id: string
  user: {
    name: string
    tag: string
  }
  title: string
  time: string
  location: string
  spotsLeft: number
  tasteTags: string[]
  interestTags: string[]
  city: string
  category: string
  schedule: ActivitySchedule
  budget: ActivityBudget
  restaurant?: string
  address?: string
}

export const mockActivities: Activity[] = [
  {
    id: 'a1',
    user: { name: 'Mia', tag: 'Grad student' },
    title: 'Yunnan dinner in Shoreditch — spicy food lovers welcome',
    time: 'May 24 · 6:30 PM',
    location: 'Yun · Shoreditch',
    spotsLeft: 2,
    tasteTags: ['Yunnan', 'Spicy'],
    interestTags: ['Food crawl', 'Easy hang'],
    city: 'London',
    category: 'Dining',
    schedule: 'weekend',
    budget: 'mid',
    restaurant: 'Yun',
    address: '1-3 Rivington St, London EC2A 3DT',
  },
  {
    id: 'a2',
    user: { name: 'Ryan', tag: 'Tech' },
    title: 'After-work drinks at Canary Wharf — craft beer or cocktails',
    time: 'May 23 · 7:00 PM',
    location: 'The Gun · Canary Wharf',
    spotsLeft: 1,
    tasteTags: ['Craft beer', 'Cocktails'],
    interestTags: ['Career chat', 'Easy hang'],
    city: 'London',
    category: 'Drinks',
    schedule: 'tomorrow',
    budget: 'mid',
    restaurant: 'The Gun',
    address: '27 Coldharbour, London E14 9NS',
  },
  {
    id: 'a3',
    user: { name: 'Suki', tag: 'Finance' },
    title: 'Midtown sushi lunch — good food, no shop talk',
    time: 'May 22 · 12:00 PM',
    location: 'Sushi of Gari 46 · Midtown',
    spotsLeft: 1,
    tasteTags: ['Sushi', 'Japanese'],
    interestTags: ['Foodie', 'Low-key'],
    city: 'NYC',
    category: 'Dining',
    schedule: 'today',
    budget: 'mid',
    restaurant: 'Sushi of Gari 46',
    address: '347 W 46th St, New York, NY 10036',
  },
  {
    id: 'a4',
    user: { name: 'Zack', tag: 'Grad student' },
    title: 'Hot pot in Flushing — Haidilao or Chongqing Lao Zao',
    time: 'May 25 · 5:00 PM',
    location: 'Chongqing Lao Zao · Flushing',
    spotsLeft: 3,
    tasteTags: ['Hot pot', 'Extra spicy'],
    interestTags: ['Hot pot crew', 'Food crawl'],
    city: 'NYC',
    category: 'Dining',
    schedule: 'weekend',
    budget: 'mid',
    restaurant: 'Chongqing Lao Zao',
    address: '37-04 Prince St, Flushing, NY 11354',
  },
  {
    id: 'a5',
    user: { name: 'Zack', tag: 'Grad student' },
    title: 'Sunday KTV — Canto-pop hits, Eason fans welcome',
    time: 'May 26 · 2:00 PM',
    location: 'Popular KTV · Flushing',
    spotsLeft: 2,
    tasteTags: ['Karaoke', 'Canto-pop'],
    interestTags: ['Karaoke', 'Night owl'],
    city: 'NYC',
    category: 'KTV',
    schedule: 'weekend',
    budget: 'low',
    restaurant: 'Popular KTV',
    address: '136-20 Roosevelt Ave, Flushing, NY 11354',
  },
  {
    id: 'a6',
    user: { name: 'Emma', tag: 'Healthcare' },
    title: 'Dim sum brunch in Chatswood — off-duty vibes only',
    time: 'May 24 · 10:00 AM',
    location: 'Harbour Restaurant · Chatswood',
    spotsLeft: 2,
    tasteTags: ['Dim sum', 'Cantonese'],
    interestTags: ['Deep convo', 'Easy hang'],
    city: 'Sydney',
    category: 'Dining',
    schedule: 'weekend',
    budget: 'mid',
    restaurant: 'Harbour Restaurant',
    address: 'Shop 18, 427-441 Victoria Ave, Chatswood NSW 2067',
  },
  {
    id: 'a7',
    user: { name: 'Alex', tag: 'Tech' },
    title: 'Specialty coffee crawl in Haymarket — photo-friendly spots',
    time: 'May 23 · 3:00 PM',
    location: 'Single O · Haymarket',
    spotsLeft: 1,
    tasteTags: ['Coffee', 'Photos'],
    interestTags: ['Coffee lover', 'Food crawl'],
    city: 'Sydney',
    category: 'Coffee',
    schedule: 'tomorrow',
    budget: 'low',
    restaurant: 'Single O Surry Hills',
    address: '12-16 Dixon St, Haymarket NSW 2000',
  },
  {
    id: 'a8',
    user: { name: 'Alex', tag: 'Tech' },
    title: 'Thai dinner in Bondi, then sunset walk',
    time: 'May 25 · 6:00 PM',
    location: 'Thai Foon · Bondi Beach',
    spotsLeft: 2,
    tasteTags: ['Thai', 'Beach'],
    interestTags: ['Hiking', 'Easy hang'],
    city: 'Sydney',
    category: 'Dining',
    schedule: 'weekend',
    budget: 'mid',
    restaurant: 'Thai Foon',
    address: '139-141 Bondi Rd, Bondi Beach NSW 2026',
  },
  {
    id: 'a9',
    user: { name: 'Jen', tag: 'Grad student' },
    title: 'HK-style brunch in Markham — PhD life & pop culture chat',
    time: 'May 24 · 11:00 AM',
    location: 'Full Love Restaurant · Markham',
    spotsLeft: 1,
    tasteTags: ['HK cafe', 'Milk tea'],
    interestTags: ['Budget-friendly', 'Easy hang'],
    city: 'Toronto',
    category: 'Dining',
    schedule: 'weekend',
    budget: 'low',
    restaurant: 'Full Love Restaurant',
    address: '3235 Hwy 7 E, Markham, ON L3R 3P3',
  },
  {
    id: 'a10',
    user: { name: 'James', tag: 'Finance' },
    title: 'Whiskey night downtown — immigrant stories welcome',
    time: 'May 23 · 8:00 PM',
    location: 'Bar Chef · Downtown Toronto',
    spotsLeft: 2,
    tasteTags: ['Whiskey', 'Cocktails'],
    interestTags: ['Whiskey', 'Deep convo'],
    city: 'Toronto',
    category: 'Drinks',
    schedule: 'tomorrow',
    budget: 'high',
    restaurant: 'Bar Chef',
    address: '488 Wellington St W, Toronto, ON M5V 1E9',
  },
  {
    id: 'a11',
    user: { name: 'James', tag: 'Finance' },
    title: 'Private Cantonese dinner — parents visiting, my treat',
    time: 'May 28 · 6:30 PM',
    location: 'Lee Chuen Kitchen · Unionville',
    spotsLeft: 4,
    tasteTags: ['Cantonese', 'Private kitchen'],
    interestTags: ['Cantonese', 'Deep convo'],
    city: 'Toronto',
    category: 'Dining',
    schedule: 'weekend',
    budget: 'high',
    restaurant: 'Lee Chuen Kitchen',
    address: '8360 Kennedy Rd, Unionville, ON L3R 9W4',
  },
  {
    id: 'a12',
    user: { name: 'Lisa', tag: 'Healthcare' },
    title: 'Hainanese chicken rice near Orchard — local favorite',
    time: 'May 22 · 12:30 PM',
    location: 'Tian Tian · Maxwell',
    spotsLeft: 1,
    tasteTags: ['Chicken rice', 'Hawker'],
    interestTags: ['Southeast Asian', 'Budget-friendly'],
    city: 'Singapore',
    category: 'Dining',
    schedule: 'today',
    budget: 'low',
    restaurant: 'Tian Tian',
    address: '1 Kadayanallur St, Maxwell Food Centre, Singapore 069184',
  },
  {
    id: 'a13',
    user: { name: 'Han', tag: 'Tech' },
    title: 'Hot pot after work at One-North — mild or spicy',
    time: 'May 23 · 7:30 PM',
    location: 'Coca Hotpot · Orchard',
    spotsLeft: 2,
    tasteTags: ['Hot pot', 'Taiwanese'],
    interestTags: ['Hot pot crew', 'Night owl'],
    city: 'Singapore',
    category: 'Dining',
    schedule: 'tomorrow',
    budget: 'mid',
    restaurant: 'Coca Hotpot',
    address: '391 Orchard Rd, Ngee Ann City, Singapore 238872',
  },
  {
    id: 'a14',
    user: { name: 'Mia', tag: 'Grad student' },
    title: 'Kusama at Tate Modern — ticket booked, need 1 more',
    time: 'May 26 · 2:00 PM',
    location: 'Tate Modern · South Bank',
    spotsLeft: 1,
    tasteTags: ['Art', 'Afternoon tea'],
    interestTags: ['Art', 'Deep talk'],
    city: 'London',
    category: 'Art',
    schedule: 'weekend',
    budget: 'mid',
    restaurant: 'OXO Tower Restaurant',
    address: 'Barge House St, London SE1 9PH',
  },
  {
    id: 'a15',
    user: { name: 'Suki', tag: 'Finance' },
    title: 'Matcha coffee crawl in SoHo — Butler & nearby spots',
    time: 'May 24 · 10:30 AM',
    location: 'Butler · SoHo',
    spotsLeft: 1,
    tasteTags: ['Matcha', 'Coffee'],
    interestTags: ['Coffee lover', 'Food crawl'],
    city: 'NYC',
    category: 'Coffee',
    schedule: 'weekend',
    budget: 'low',
    restaurant: 'Butler',
    address: '95 W Broadway, New York, NY 10007',
  },
]
