export type ActivitySchedule = 'today' | 'tomorrow' | 'weekend'
export type ActivityBudget = 'low' | 'mid' | 'high'

export interface Activity {
  id: string
  user: {
    name: string
    tag: string
  }
  title: string
  time: string
  location: string
  spotsLeft: number
  tasteTags: string[]
  interestTags: string[]
  city: string
  category: string
  schedule: ActivitySchedule
  budget: ActivityBudget
  restaurant?: string
  address?: string
}

export const mockActivities: Activity[] = [
  {
    id: 'a1',
    user: { name: '小雨', tag: '留学生' },
    title: '周六晚组个云南菜局，人均30镑左右，能吃辣的来',
    time: '5月24日 18:30',
    location: 'Yun · Shoreditch',
    spotsLeft: 2,
    tasteTags: ['云南菜', '能吃辣'],
    interestTags: ['探店打卡', '随性聊天'],
    city: '伦敦',
    category: '吃饭',
    schedule: 'weekend',
    budget: 'mid',
    restaurant: 'Yun',
    address: '1-3 Rivington St, London EC2A 3DT',
  },
  {
    id: 'a2',
    user: { name: '浩然', tag: 'IT外派' },
    title: 'Canary Wharf 下班喝一杯，精酿或鸡尾酒都行',
    time: '5月23日 19:00',
    location: 'The Gun · Canary Wharf',
    spotsLeft: 1,
    tasteTags: ['精酿', '鸡尾酒'],
    interestTags: ['职场交流', '随性聊天'],
    city: '伦敦',
    category: '喝酒',
    schedule: 'tomorrow',
    budget: 'mid',
    restaurant: 'The Gun',
    address: '27 Coldharbour, London E14 9NS',
  },
  {
    id: 'a3',
    user: { name: '思琪', tag: '金融' },
    title: 'Midtown 午餐约个日料，不聊 KPI 只聊好吃的',
    time: '5月22日 12:00',
    location: 'Sushi of Gari 46 · Midtown',
    spotsLeft: 1,
    tasteTags: ['日料', '寿司'],
    interestTags: ['Foodie', '安静聚餐'],
    city: '纽约',
    category: '吃饭',
    schedule: 'today',
    budget: 'mid',
    restaurant: 'Sushi of Gari 46',
    address: '347 W 46th St, New York, NY 10036',
  },
  {
    id: 'a4',
    user: { name: '子轩', tag: '留学生' },
    title: '法拉盛火锅局！海底捞或重庆老灶二选一',
    time: '5月25日 17:00',
    location: '重庆老灶火锅 · Flushing',
    spotsLeft: 3,
    tasteTags: ['火锅', '重辣'],
    interestTags: ['火锅局', '川渝老乡'],
    city: '纽约',
    category: '吃饭',
    schedule: 'weekend',
    budget: 'mid',
    restaurant: '重庆老灶火锅',
    address: '37-04 Prince St, Flushing, NY 11354',
  },
  {
    id: 'a5',
    user: { name: '子轩', tag: '留学生' },
    title: '周日 K 歌，港乐金曲局，会唱陈奕迅的优先',
    time: '5月26日 14:00',
    location: 'Popular KTV · Flushing',
    spotsLeft: 2,
    tasteTags: ['K歌', '港乐'],
    interestTags: ['K歌达人', '港乐迷'],
    city: '纽约',
    category: 'KTV',
    schedule: 'weekend',
    budget: 'low',
    restaurant: 'Popular KTV',
    address: '136-20 Roosevelt Ave, Flushing, NY 11354',
  },
  {
    id: 'a6',
    user: { name: '欣怡', tag: '医疗' },
    title: '休息日早茶走起，Chatswood 海港酒家见',
    time: '5月24日 10:00',
    location: '海港酒家 · Chatswood',
    spotsLeft: 2,
    tasteTags: ['早茶', '粤菜'],
    interestTags: ['川渝老乡', '深度交流'],
    city: '悉尼',
    category: '吃饭',
    schedule: 'weekend',
    budget: 'mid',
    restaurant: '海港酒家',
    address: 'Shop 18, 427-441 Victoria Ave, Chatswood NSW 2067',
  },
  {
    id: 'a7',
    user: { name: '一鸣', tag: 'IT外派' },
    title: 'Haymarket 精品咖啡探店，拍照好看那种',
    time: '5月23日 15:00',
    location: 'Single O · Haymarket',
    spotsLeft: 1,
    tasteTags: ['咖啡', '拍照'],
    interestTags: ['咖啡控', '打卡探店'],
    city: '悉尼',
    category: '咖啡',
    schedule: 'tomorrow',
    budget: 'low',
    restaurant: 'Single O Surry Hills',
    address: '12-16 Dixon St, Haymarket NSW 2000',
  },
  {
    id: 'a8',
    user: { name: '一鸣', tag: 'IT外派' },
    title: 'Bondi 海边吃完晚饭看日落，泰餐走起',
    time: '5月25日 18:00',
    location: 'Thai Foon · Bondi Beach',
    spotsLeft: 2,
    tasteTags: ['泰餐', '海边'],
    interestTags: ['徒步', '随性聊天'],
    city: '悉尼',
    category: '吃饭',
    schedule: 'weekend',
    budget: 'mid',
    restaurant: 'Thai Foon',
    address: '139-141 Bondi Rd, Bondi Beach NSW 2026',
  },
  {
    id: 'a9',
    user: { name: '慧敏', tag: '留学生' },
    title: '万锦港式茶餐厅 brunch，聊 PhD 辛酸也聊综艺',
    time: '5月24日 11:00',
    location: '富来茶餐厅 · Markham',
    spotsLeft: 1,
    tasteTags: ['港式', '奶茶'],
    interestTags: ['港乐迷', '预算友好'],
    city: '多伦多',
    category: '吃饭',
    schedule: 'weekend',
    budget: 'low',
    restaurant: '富来茶餐厅',
    address: '3235 Hwy 7 E, Markham, ON L3R 3P3',
  },
  {
    id: 'a10',
    user: { name: '俊杰', tag: '金融' },
    title: 'Downtown 威士忌吧小酌，聊聊移民那些事儿',
    time: '5月23日 20:00',
    location: 'Bar Chef · Downtown Toronto',
    spotsLeft: 2,
    tasteTags: ['威士忌', '鸡尾酒'],
    interestTags: ['威士忌', '深度交流'],
    city: '多伦多',
    category: '喝酒',
    schedule: 'tomorrow',
    budget: 'high',
    restaurant: 'Bar Chef',
    address: '488 Wellington St W, Toronto, ON M5V 1E9',
  },
  {
    id: 'a11',
    user: { name: '俊杰', tag: '金融' },
    title: '粤菜私房菜聚餐，父母来加想请客顺便交朋友',
    time: '5月28日 18:30',
    location: '李泉私房菜 · Unionville',
    spotsLeft: 4,
    tasteTags: ['粤菜', '私房菜'],
    interestTags: ['粤语', '深度交流'],
    city: '多伦多',
    category: '吃饭',
    schedule: 'weekend',
    budget: 'high',
    restaurant: '李泉私房菜',
    address: '8360 Kennedy Rd, Unionville, ON L3R 9W4',
  },
  {
    id: 'a12',
    user: { name: '嘉欣', tag: '医疗' },
    title: '乌节路附近海南鸡饭，本地人带路不踩雷',
    time: '5月22日 12:30',
    location: '天天海南鸡饭 · Maxwell',
    spotsLeft: 1,
    tasteTags: ['海南鸡饭', '小贩中心'],
    interestTags: ['东南亚美食', '预算友好'],
    city: '新加坡',
    category: '吃饭',
    schedule: 'today',
    budget: 'low',
    restaurant: '天天海南鸡饭',
    address: '1 Kadayanallur St, Maxwell Food Centre, Singapore 069184',
  },
  {
    id: 'a13',
    user: { name: '承翰', tag: 'IT外派' },
    title: 'One-North 下班火锅，台式麻辣或清汤你选',
    time: '5月23日 19:30',
    location: 'Coca Hotpot · Orchard',
    spotsLeft: 2,
    tasteTags: ['火锅', '台式'],
    interestTags: ['火锅局', '夜猫子'],
    city: '新加坡',
    category: '吃饭',
    schedule: 'tomorrow',
    budget: 'mid',
    restaurant: 'Coca Hotpot',
    address: '391 Orchard Rd, Ngee Ann City, Singapore 238872',
  },
  {
    id: 'a14',
    user: { name: '小雨', tag: '留学生' },
    title: 'Tate Modern 草间弥生特展，票已买好差一位',
    time: '5月26日 14:00',
    location: 'Tate Modern · South Bank',
    spotsLeft: 1,
    tasteTags: ['艺术', '下午茶'],
    interestTags: ['艺术', 'Deep talk'],
    city: '伦敦',
    category: '看展',
    schedule: 'weekend',
    budget: 'mid',
    restaurant: 'OXO Tower Restaurant',
    address: 'Barge House St, London SE1 9PH',
  },
  {
    id: 'a15',
    user: { name: '思琪', tag: '金融' },
    title: 'SoHo 网红咖啡打卡，抹茶控集合',
    time: '5月24日 10:30',
    location: 'Butler · SoHo',
    spotsLeft: 1,
    tasteTags: ['抹茶', '咖啡'],
    interestTags: ['咖啡控', '打卡探店'],
    city: '纽约',
    category: '咖啡',
    schedule: 'weekend',
    budget: 'low',
    restaurant: 'Butler',
    address: '95 W Broadway, New York, NY 10007',
  },
]
